state ::= identifier, [':', EXPR] ;
property ::= 'p.', identifier, { '.', identifier } ;
node_property ::= 'n.', identifier, { '.', identifier } ;
assignment ::= (property | node_property), '=', EXPR ;
node ::= 'node', identifier, [ 'meta', block ], block ;
block ::= '{', { EXPR }, '}' ;
identifier ::= /[a-zA-Z_][a-zA-Z_\d]*/ ;
